src/Entity/Entreprise.php
<?php

namespace App\Entity;

use App\Repository\EntrepriseRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EntrepriseRepository::class)]
class Entreprise
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $raisonSociale = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateCreation = null;

    #[ORM\Column(length: 100)]
    private ?string $adresse = null;

    #[ORM\Column(length: 20)]
    private ?string $codePostal = null;

    #[ORM\Column(length: 50)]
    private ?string $ville = null;

    /**
     * @var Collection<int, Employe>
     */
    #[ORM\OneToMany(targetEntity: Employe::class, mappedBy: 'entreprise', orphanRemoval: true)]
    #[ORM\OrderBy(["nom" => "ASC"])] // on veut trier les employés par ordre alphabétique de nom. (pour la liste d'employés de chaque entreprise dans la vue "détal d'une entreprise")
    private Collection $employes;

    public function __construct()
    {
        $this->employes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRaisonSociale(): ?string
    {
        return $this->raisonSociale;
    }

    public function setRaisonSociale(string $raisonSociale): static
    {
        $this->raisonSociale = $raisonSociale;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->dateCreation;
    }

    public function getDateCreationString(): ?string
    {
        return $this->dateCreation->format("d-m-Y");
    }

    public function setDateCreation(\DateTimeInterface $dateCreation): static
    {
        $this->dateCreation = $dateCreation;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): static
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->codePostal;
    }

    public function setCodePostal(string $codePostal): static
    {
        $this->codePostal = $codePostal;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): static
    {
        $this->ville = $ville;

        return $this;
    }

    // je crée une fonction pour obtenir l'adresse complète rapidement
    public function getAdresseComplete(): ?string
    {
        return $this->adresse." ".$this->codePostal." ".$this->ville;
    }

    /**
     * @return Collection<int, Employe>
     */
    public function getEmployes(): Collection
    {
        return $this->employes;
    }

    public function addEmploye(Employe $employe): static
    {
        if (!$this->employes->contains($employe)) {
            $this->employes->add($employe);
            $employe->setEntreprise($this);
        }

        return $this;
    }

    public function removeEmploye(Employe $employe): static
    {
        if ($this->employes->removeElement($employe)) {
            // set the owning side to null (unless already changed)
            if ($employe->getEntreprise() === $this) {
                $employe->setEntreprise(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->raisonSociale."  (".$this->codePostal." ".$this->ville.")";
    }

}

src/Form/EntrepriseType.php
<?php

namespace App\Form;

use App\Entity\Entreprise;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class EntrepriseType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        // partie construction du formulaire avec les bonnes indications de données
        $builder
            ->add('raisonSociale', TextType::class, [
                'attr' => [
                    'class' => 'form-control' // équivaut à attribuer la valeur 'form-control' à l'attribut 'class' dans la balise input -> <input type="text" id="name" name="name" class="form-control" />
                ]
            ])

            ->add('dateCreation', null, [
                'attr' => [
                    'class' => 'form-control' // équivaut à attribuer la valeur 'form-control' à l'attribut 'class' dans la balise input -> <input type="text" id="name" name="name" class="form-control" />
                ],
                'widget' => 'single_text',
            ], DateType::class) // attention à l'ordre des arguments !

            ->add('adresse', TextType::class, [
                'attr' => [
                    'class' => 'form-control' // équivaut à attribuer la valeur 'form-control' à l'attribut 'class' dans la balise input -> <input type="text" id="name" name="name" class="form-control" />
                ]
            ])

            ->add('codePostal', TextType::class, [
                'attr' => [
                    'class' => 'form-control' // équivaut à attribuer la valeur 'form-control' à l'attribut 'class' dans la balise input -> <input type="text" id="name" name="name" class="form-control" />
                ]
            ])

            ->add('ville', TextType::class, [
                'attr' => [
                    'class' => 'form-control' // équivaut à attribuer la valeur 'form-control' à l'attribut 'class' dans la balise input -> <input type="text" id="name" name="name" class="form-control" />
                ]
            ])


            // je rajoute à la main un bouton pour valider le formulaire
            ->add('valider', SubmitType::class, [
                'attr' => [
                    'class' => 'btn btn-primary' // équivaut à attribuer la valeur 'form-control' à l'attribut 'class' dans la balise input -> <input type="text" id="name" name="name" class="form-control" />
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Entreprise::class,
        ]);
    }
}

src/Controller/EntrepriseController.php
<?php

namespace App\Controller;

use App\Entity\Entreprise;
use App\Repository\EntrepriseRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use App\Form\EntrepriseType; // importée car besoin dans public function new()

class EntrepriseController extends AbstractController
{
    // dans le navigateur, http://127.0.0.1:8000/entreprise pour afficher cette vue ... l'argument '/entreprise' de Route est donc importante
    //on peut changer le name mais il faut vraiment qu'il soit unique car il servira pour du routage plus tard
    #[Route('/entreprise', name: 'app_entreprise')]

    // methode index qui renvoie une réponse
    // le render est la méthode qui permet de faire le lien entre le controller et la vue
    // (ancienne écriture) -> public function index(EntityManagerInterface $entityManager): Response
    public function index(EntrepriseRepository $entrepriseRepository): Response
    {

        // j'attribue une valeur directement dans le controleur
        $name1 = 'test de variable';
        $tableau = ["value1", "value2", "value3", "value4"];


        // ici, on va récupérer les données dans notre base de données $bidule = (va chercher dans la BDD) -> doctrine fera la relation entre le projet et la BDD. (dans le return, on crée aussi 'entreprise' pour la passer à la vue)
        // en l'ocurrence, on a récup toutes les entreprises de notre BDD, qu'on va envoyer via la méthode render dans la vue entreprise/index.html.twig 
        // (ancienne écriture) -> $entreprises = $entityManager->getRepository(Entreprise::class)->findAll();
        // findAll -> $entreprises = $entrepriseRepository->findAll();
        $entreprises = $entrepriseRepository->findBy([], ["raisonSociale"=> "ASC"]);
        // équivaut à -> SELECT * FROM entreprise ORDER BY raisonSociale ASC
        // agit sur notre affichage dans la vue

        $entreprises2 = $entrepriseRepository->findBy(["ville" => "STRASBOURG"], ['raisonSociale'=> "ASC"]);
        // on ne veut que les entreprises qui sont sur Strasbourg
        // équivaut à -> SELECT * FROM entreprise WHERE ville = 'STRASBOURG' ORDER BY raisonSociale ASC

        $entreprises3 = $entrepriseRepository->findBy([], ['raisonSociale'=> "DESC"]);
        
 
        
        // 'entreprise/index.html.twig' -> chemin vers la vue (c'est en effet dans le dossier entreprise, c'est bien le fichier index.html.twig -> les infos vont là bas)
        return $this->render('entreprise/index.html.twig', [

            // argument par défaut(on peut avoir 0 argument) pour montrer comment faire passer un argument dans la vue -> dans entreprise/index.html.twig, on a donc {{ controller_name }}
            'controller_name' => 'EntrepriseController',

            'name' => 'Elan Formation',

            'name1' => $name1,

            'tableau' => $tableau,

            // je crée aussi une variable entreprises qu'on passera à la vue.
            'entreprises' => $entreprises,

            'entreprises2' => $entreprises2,

            'entreprises3' => $entreprises3,

        ]);
    }






    // #[Route('/entreprise/{id}', name: 'show_entreprise')] -> on copie colle et on adapte à la fonction new()
    #[Route('/entreprise/new', name: 'new_entreprise')] // 'new_entreprise' est un nom cohérent qui décrit bien la fonction attendue

    // ajout d'une deuxième route car la méthode new_edit() sert également à modifier une entreprise de notre BDD
    #[Route('/entreprise/{id}/edit', name: 'edit_entreprise')] // 'edit_entreprise' est un nom cohérent qui décrit bien la fonction attendue

    // https://symfony.com/doc/current/forms.html#rendering-forms
    /*
    public function new(Request $request): Response
    {
        $task = new Task();
        // ...

        $form = $this->createForm(TaskType::class, $task);

        return $this->render('task/new.html.twig', [
            'form' => $form,
        ]);
    }
    */
    public function new_edit(Entreprise $entreprise = null, Request $request, EntityManagerInterface $entityManager): Response // pour ajouter une entreprise à la BDD (ou modifier une entreprise dans la BDD : public function new() s'appelle désormais public function new_edit() )
    {
        /* 
        ancien 1. on crée une nouvelle entreprise (un objet entreprise est bien créé ici)
        $entreprise = new Entreprise();
        */

        // 1. si pas d'entreprise, on crée une nouvelle entreprise (un objet entreprise est bien créé ici) - si elle existe déjà, pas besoin de la créer
        if(!$entreprise) {
            $entreprise = new Entreprise();
        }


        // 2. on crée le formulaire à partir de EntrepriseType (on veut ce modèle là bien entendu)
        $form = $this->createForm(EntrepriseType::class, $entreprise); // c'est bien la méthode createForm() qui permet de créer le formulaire


        // 4. le traitement s'effectue ici ! si le formulaire soumis est correct, on fera l'insertion en BDD
        /*
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            // $form->getData() holds the submitted values
            // but, the original `$task` variable has also been updated
            $task = $form->getData();

            // ... perform some action, such as saving the task to the database

            return $this->redirectToRoute('task_success');
        }
        */
        $form->handleRequest($request);


        // bloc qui concerne la soumission
        if ($form->isSubmitted() && $form->isValid()) {
            
            $entreprise = $form->getData(); // on récupère les données du formulaire dans notre objet entreprise
            
            $entityManager->persist($entreprise); // équivaut à la méthode prepare() en PDO

            $entityManager->flush(); // équivaut à la méthode execute() en PDOStatement

            // redirection vers la liste d'entreprises (si formulaire soumis et formulaire valide)
            return $this->redirectToRoute('app_entreprise');
        }


        // 3. on affiche le formulaire créé dans la page dédiée à cet affichage -> {{ form(formAddEntreprise) }} --> affichage par défaut 
        return $this->render('entreprise/new.html.twig', [ // 'entreprise/new.html.twig' -> vue dédiée à l'affichage du formulaire : on crée un nouveau fichier dans le dossier entreprise
            // 'form' => $form,  on fait passer une variable form qui prend la valeur $form
            // on change le nom pour éviter toute ambiguité 'form' -> 'formAddEntreprise' comme expliqué dans new.html.twig
            'formAddEntreprise' => $form,
            'edit' => $entreprise->getId() // comportement booléen 
        ]);
    }


    // {id} sera l'identifiant de l'entreprise choisie -> dans Entity/Entreprise, $id sert bien à identifier chaque objet $entreprise
    #[Route('/entreprise/{id}/delete', name: 'delete_entreprise')]
    public function delete(Entreprise $entreprise, EntityManagerInterface $entityManager): Response
    {
        $entityManager->remove($entreprise); // on enlève l'entreprise ciblée de la collection d'entreprises
        $entityManager->flush(); // on effectue la requête SQL : DELETE FROM

        return $this->redirectToRoute('app_entreprise'); // après une suppression, on redirige vers la liste d'entreprises
    }




    // {id} sera l'identifiant de l'entreprise choisie -> dans Entity/Entreprise, $id sert bien à identifier chaque objet $entreprise
    #[Route('/entreprise/{id}', name: 'show_entreprise')]
    public function show(Entreprise $entreprise): Response
    {
        
        // on ira vers la vue show dans le dossier entreprise
        return $this->render('entreprise/show.html.twig', [

            // on fait passer l'objet $entreprise choisi
            'entreprise' => $entreprise,

        ]);
    }





}

templates/entreprise/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des entreprises{% endblock %}

{% block body %}

    <h1>Liste des entreprises</h1>


    
    <!-- 
        dans le controller, on a cela
        [
            'controller_name' => 'EntrepriseController',
        ]
        
        on se doute que la vue affichera : EntrepriseController
    -->
    {{ controller_name }}<br><br>

    Bonjour {{ name }} !<br><br>

    je teste ma variable : {{ name1 }}<br><br><br><br>

    
    <!-- le mot 'element' est choisi au pif, on peut prendre $bidule si on le souhaite -->
    {% for element in tableau %}
    
        {{ element }}<br>

    {% endfor %}<br>



    enfin j'affiche les vraies informations de l'exercice :<br><br> 
    {% for entreprise in entreprises %}
    
        <!-- $entreprise->getRaisonSociale() : on reprend les noms des entités, pas ceux de la BDD -->
        {{ entreprise.raisonSociale }}<br><br>

    {% endfor %}<br><br>



    Méthode 1 de Mickael : on concatène<br><br>
    {% for entreprise in entreprises %}
    
    
        <b>{{ entreprise.raisonSociale }}</b> {{ ' ('~ entreprise.codePostal ~ ' ' ~ entreprise.ville ~ ')' }}<br><br>
    

    {% endfor %}<br><br>


    Méthode 2 de Michael (plus simple):<br><br>
    {% for entreprise in entreprises %}
    
        <b>{{ entreprise.raisonSociale }}</b> ({{ entreprise.codePostal }} {{ entreprise.ville }})<br><br>

    {% endfor %}<br><br>


    Méthode 3 _toString :<br><br>
    {% for entreprise in entreprises %}
    
        <b>{{ entreprise }}</b> <br><br>

    {% endfor %}<br><br>


    Je ne veux que les entreprises de Strasbourg :<br><br>
    {% for entreprise in entreprises2 %}
    
        <b>{{ entreprise }}</b> <br><br>

    {% endfor %}<br><br>


    <a href="{{ path('new_entreprise') }}" class="btn btn-primary">Ajouter une entreprise</a><br><br>


    Je veux toutes les entreprises en tri DESC et je crée des liens ! :<br><br>
    {% for entreprise in entreprises3 %}
    
        <!-- tant que href est vide, on ne va nulle part, on va le compléter comme suit : 
        path('nom de la méthode qui permet de récupérer le détail d'une entreprise') et aussi l'identifiant de l'entreprise concernée -->
        <a href="{{ path('show_entreprise', {'id' : entreprise.id}) }}">{{ entreprise.raisonSociale }}</a>
        <a class="btn btn-warning" href="{{ path('edit_entreprise', {'id' : entreprise.id}) }}">Editer le profil</a> {# bouton pour éditer l'entreprise #}
        <a class="btn btn-danger" href="{{ path('delete_entreprise', {'id' : entreprise.id}) }}">Supprimer le profil</a> {# bouton pour supprimer l'entreprise #}
        <br><br>
        <!-- 'id' est bien indiqué tel quel dans l'url, c'est le terme exact de l'url -->

    {% endfor %}<br><br>


{% endblock %}

templates/entreprise/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter une entreprise{% endblock %}

{% block body %}

    {# on crée une condition en fonction de la variable edit (booléen) qui provient du controller EntrepriseController, dans la fonction new_edit() #} 
    {% if edit %}
        <h1>Editer une entreprise</h1>
    {% else %}
        <h1>Ajouter une entreprise</h1>
    {% endif %}
    

    {# {{ form(form) }} : ancienne syntaxe ambigue #} 
    {# {{ form(formAddEntreprise) }} #}



    {{ form_start(formAddEntreprise) }}

        {{ form_row(formAddEntreprise.raisonSociale) }}
        {{ form_row(formAddEntreprise.dateCreation) }}
        

        <div class="row">
            <div class="col-sm">
                {{ form_row(formAddEntreprise.adresse) }}
            </div>
            <div class="col-sm">
                {{ form_row(formAddEntreprise.codePostal) }}
            </div>
            <div class="col-sm">
                {{ form_row(formAddEntreprise.ville) }}
            </div>
        </div>
        
        {{ form_row(formAddEntreprise.valider) }}


    {{ form_end(formAddEntreprise) }}

    
{#

https://symfony.com/doc/current/forms.html#rendering-forms 

 templates/task/new.html.twig 
{{ form(form) }} -> risque de confusion avec la syntaxe form*1(form*2) 
form*1 est le nom de la fonction qui permet de récupérer le formulaire (fonction à appeler pour rendre le formulaire visible) 
l'argument form*2 dedans est le nom de la variable qui provient du controller entreprise dans la public function new() : 'form' => $form,

on va donc changer le nom de la variable dans le EntrepriseController pour éviter toute ambiguité : 'form' -> 'formAddEntreprise'

#}


{% endblock %}

templates/entreprise/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détail d'une entreprise{% endblock %}

{% block body %}

    <h1>Détail d'une entreprise</h1>  

    <h2>{{ entreprise.raisonSociale }}</h2>

    <p>
        Adresse : {{ entreprise.adresse }} {{ entreprise.codePostal }} {{ entreprise.ville }}<br>
    
        Adresse "rapide" : {{ entreprise.adresseComplete }}<br>
    
        Date de création : {{ entreprise.dateCreationString }}<br>
    
        Date de création filtrée par TWIG : {{ entreprise.dateCreation | date("m-d-Y") }}<br>
        <!-- je garde mon objet datetime et j'applique un filtre fourni par twig \{\{ objet_datetime|date("m-d-Y")  }} -->
        <!-- le filtre doit bien cprrespondre à l'objet en question -->
    </p>


    <h2>Liste des employés de l'entreprise</h2>

    <!-- dans le contexte PHP classique, on utilise count() pour savoir combien d'éléments existent dans la collection, dans le contexte TWIG, on utilise le filtre length -->
    {% if entreprise.employes | length > 0 %}

        <table class="table table-striped">
            <thead>
                <tr>
                    <th>
                        Employé
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for employe in entreprise.employes %}
                    <tr>
                        <td>
                            <a href="{{ path('show_employe', {'id' : employe.id}) }}">{{ employe }}</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        
    
    {% else %}

        <p>Aucun employé dans cette entreprise.</p>
        
    {% endif %}

    

{% endblock %}