src/Entity/Employe.php
<?php

namespace App\Entity;

use App\Repository\EmployeRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EmployeRepository::class)]
class Employe
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $nom = null;

    #[ORM\Column(length: 50)]
    private ?string $prenom = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $dateNaissance = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateEmbauche = null;

    #[ORM\ManyToOne(inversedBy: 'employes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Entreprise $entreprise = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $ville = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->dateNaissance;
    }

    public function setDateNaissance(?\DateTimeInterface $dateNaissance): static
    {
        $this->dateNaissance = $dateNaissance;

        return $this;
    }

    public function getDateEmbauche(): ?\DateTimeInterface
    {
        return $this->dateEmbauche;
    }

    public function setDateEmbauche(\DateTimeInterface $dateEmbauche): static
    {
        $this->dateEmbauche = $dateEmbauche;

        return $this;
    }

    public function getEntreprise(): ?Entreprise
    {
        return $this->entreprise;
    }

    public function setEntreprise(?Entreprise $entreprise): static
    {
        $this->entreprise = $entreprise;

        return $this;
    }

    public function __toString()
    {
        return $this->prenom." ".$this->nom;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(?string $ville): static
    {
        $this->ville = $ville;

        return $this;
    }

    public function getAge(): ?string
    {
        $now = new \DateTime();
        $interval = $this->dateNaissance->diff($now);
        return $interval->format("%Y"); // $interval est un objet de la classe DateInterval : la méthode format() n'a pas la syntaxe de la méthode format() de la classe DateTime
    }

}

src/Form/EmployeType.php
<?php

namespace App\Form;

use App\Entity\Employe;
use App\Entity\Entreprise;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class EmployeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        // partie construction du formulaire avec les bonnes indications de données
        $builder
            ->add('nom', TextType::class, [
                'attr' => [
                    'class' => 'form-control' // équivaut à attribuer la valeur 'form-control' à l'attribut 'class' dans la balise input -> <input type="text" id="name" name="name" class="form-control" />
                ]
            ])

            ->add('prenom', TextType::class, [
                'attr' => [
                    'class' => 'form-control' // équivaut à attribuer la valeur 'form-control' à l'attribut 'class' dans la balise input -> <input type="text" id="name" name="name" class="form-control" />
                ]
            ])

            ->add('dateNaissance', null, [
                'attr' => [
                    'class' => 'form-control' // équivaut à attribuer la valeur 'form-control' à l'attribut 'class' dans la balise input -> <input type="text" id="name" name="name" class="form-control" />
                ],
                'widget' => 'single_text',
            ], DateType::class) // attention à l'ordre des arguments !

            ->add('dateEmbauche', null, [
                'attr' => [
                    'class' => 'form-control' // équivaut à attribuer la valeur 'form-control' à l'attribut 'class' dans la balise input -> <input type="text" id="name" name="name" class="form-control" />
                ],
                'widget' => 'single_text',
            ], DateType::class) // attention à l'ordre des arguments !

            ->add('ville', TextType::class, [
                'required' => false, // on rend ce champ non obligatoire dans la saisie de notre formulaire : seul moyen possible
                'attr' => [
                    'class' => 'form-control' // équivaut à attribuer la valeur 'form-control' à l'attribut 'class' dans la balise input -> <input type="text" id="name" name="name" class="form-control" />
                ]
            ])

            ->add('entreprise', EntityType::class, [
                'class' => Entreprise::class,
                'attr' => [
                    'class' => 'form-control' // équivaut à attribuer la valeur 'form-control' à l'attribut 'class' dans la balise input -> <input type="text" id="name" name="name" class="form-control" />
                ],

                // 'choice_label' => 'id',
                'choice_label' => 'raisonSociale', // si je n'ai pas de choice_label, il affichera ce qu'il récupère dans __toString() de Entreprise. choice_label ne peut être qu'un champ.
            ]) // faire attention à ce type ! 


            // je rajoute à la main un bouton pour valider le formulaire
            ->add('valider', SubmitType::class, [
                'attr' => [
                    'class' => 'btn btn-primary' // équivaut à attribuer la valeur 'form-control' à l'attribut 'class' dans la balise input -> <input type="text" id="name" name="name" class="form-control" />
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Employe::class,
        ]);
    }
}

src/Controller/EmployeController.php
<?php

namespace App\Controller;

use App\Entity\Employe;
use App\Form\EmployeType;
use App\Repository\EmployeRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class EmployeController extends AbstractController
{
    #[Route('/employe', name: 'app_employe')]
    public function index(EmployeRepository $employeRepository): Response
    {

    // $employes = $employeRepository->findAll();
    $employes = $employeRepository->findby([], ['nom'=>'ASC']);
    // équivaut à -> SELECT * FROM employe ORDER BY nom ASC
    // agit sur notre affichage dans la vue

        return $this->render('employe/index.html.twig', [
            'employes' => $employes,
        ]);
    }





    // #[Route('/employe/{id}', name: 'show_employe')] -> on copie colle et on adapte à la fonction new()
    #[Route('/employe/new', name: 'new_employe')] // 'new_employe' est un nom cohérent qui décrit bien la fonction

    // ajout d'une deuxième route car la méthode new_edit() sert également à modifier un employé de notre BDD
    #[Route('/employe/{id}/edit', name: 'edit_employe')] // 'edit_employe' est un nom cohérent qui décrit bien la fonction attendue

    // https://symfony.com/doc/current/forms.html#rendering-forms
    /*
    public function new(Request $request): Response
    {
        $task = new Task();
        // ...

        $form = $this->createForm(TaskType::class, $task);

        return $this->render('task/new.html.twig', [
            'form' => $form,
        ]);
    }
    */

    public function new_edit(Employe $employe = null, Request $request, EntityManagerInterface $entityManager): Response // pour ajouter une entreprise à notre BDD
    {
        /* 
        ancien 1. on crée un nouvel employé (un objet employe est bien créé ici)
        $employe = new Employe();
        */

        // 1. si pas d'employé, on crée un nouvel employé (un objet employe est bien créé ici) - s'il existe déjà, pas besoin de le créer
        if(!$employe) {
            $employe = new Employe();
        }


        // 2. on crée le formulaire à partir de EmployeType (on veut ce modèle là bien entendu)
        $form = $this->createForm(EmployeType::class, $employe); // c'est bien la méthode createForm() qui permet de créer le formulaire

        // 4. le traitement s'effectue ici ! si le formulaire soumis est correct, on fera l'insertion en BDD
        /*
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            // $form->getData() holds the submitted values
            // but, the original `$task` variable has also been updated
            $task = $form->getData();

            // ... perform some action, such as saving the task to the database

            return $this->redirectToRoute('task_success');
        }
        */
        $form->handleRequest($request);


        // bloc qui concerne la soumission
        if ($form->isSubmitted() && $form->isValid()) {
            
            $employe = $form->getData(); // on récupère les données du formulaire dans notre objet entreprise
            
            $entityManager->persist($employe); // équivaut à la méthode prepare() en PDO

            $entityManager->flush(); // équivaut à la méthode execute() en PDOStatement

            // redirection vers la liste d'entreprises (si formulaire soumis et formulaire valide)
            return $this->redirectToRoute('app_employe');
        }


        // 3. on affiche le formulaire créé dans la page dédiée à cet affichage -> {{ form(formAddEntreprise) }} --> affichage par défaut 
        return $this->render('employe/new.html.twig', [ // 'employe/new.html.twig' -> vue dédiée à l'affichage du formulaire : on crée un nouveau fichier dans le dossier employe
            // 'form' => $form,  on fait passer une variable form qui prend la valeur $form
            // on change le nom pour éviter toute ambiguité 'form' -> 'formAddEmploye' comme expliqué dans new.html.twig
            'formAddEmploye' => $form,
            'edit' => $employe->getId() // comportement booléen
        ]);
    }




    // {id} sera l'identifiant de l'employé choisi -> dans Entity/Employe, $id sert bien à identifier chaque objet $employe
    #[Route('/employe/{id}/delete', name: 'delete_employe')]
    public function delete(Employe $employe, EntityManagerInterface $entityManager): Response
    {
        $entityManager->remove($employe); // on enlève l'employé ciblé de la collection d'employés
        $entityManager->flush(); // on effectue la requête SQL : DELETE FROM

        return $this->redirectToRoute('app_employe'); // après une suppression, on redirige vers la liste d'employés
    }





    // {id} sera l'identifiant de l'employé choisi -> dans Entity/Employe, $id sert bien à identifier chaque objet $employe
    #[Route('/employe/{id}', name: 'show_employe')]
    public function show(Employe $employe): Response
    {
        
        // on ira vers la vue show dans le dossier employe
        return $this->render('employe/show.html.twig', [

            // on fait passer l'objet $entreprise choisi
            'employe' => $employe,

        ]);
    }

}

templates/employe/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des employés{% endblock %}

{% block body %}
    <h1>Liste des employés</h1>

    <a href="{{ path('new_employe') }}" class="btn btn-primary">Ajouter un employé</a><br><br>

    J'affiche le nom et prénom de chaque employé :<br><br>
    {% for employe in employes %}
    
    <b>{{ employe }}</b> <br><br>

    {% endfor %}<br><br>

    J'affiche le nom et prénom de chaque employé et la raison sociale de son entreprise :<br><br>
    {% for employe in employes %}
    
    <b>{{ employe }} ({{ employe.entreprise.raisonSociale }}) </b> <br><br>

    {% endfor %}<br><br>

    J'affiche le nom et prénom de chaque employé (avec un lien !! ) et la raison sociale "longue" (grace à __toString()) :<br><br>
    {% for employe in employes %}
    
    <a href="{{ path('show_employe', {'id' : employe.id}) }}">{{ employe }}</a> {{ employe.entreprise }}
    <a class="btn btn-warning" href="{{ path('edit_employe', {'id' : employe.id}) }}">Editer le profil</a> {# bouton pour éditer l'employé #}
    <a class="btn btn-danger" href="{{ path('delete_employe', {'id' : employe.id}) }}">Supprimer le profil</a> {# bouton pour supprimer l'employé #}
    <br><br>

    {% endfor %}<br><br>


{% endblock %}

templates/employe/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un employé{% endblock %}

{% block body %}

    <h1>Ajouter un employé</h1>

    
    {# {{ form(form) }} : ancienne syntaxe ambigue rtemplacée par celle en dessous #}
    {# {{ form(formAddEmploye) }} => cette ligne ne permet pas d'avoir bcp de controle sur l'affichage du formulaire. #}
    


    {# 1er affichage #}
    {# {{ form(formAddEmploye) }} => on le remplace par le bloc en dessous, qui offre plus de liberté pour manipuler le formulaire #}

    
    {# 2eme affichage => même résultat que le premier #}
    {# {{ form_start(formAddEmploye) }}

        {{ form_row(formAddEmploye.nom) }}  nom_du_formulaire.nom_du_champ => nom des champs de la fonction buildForm() dans EmployeType.php 
        {{ form_row(formAddEmploye.prenom) }}
        {{ form_row(formAddEmploye.dateNaissance) }}
        {{ form_row(formAddEmploye.dateEmbauche) }}
        {{ form_row(formAddEmploye.entreprise) }}
        {{ form_row(formAddEmploye.ville) }}
        {{ form_row(formAddEmploye.valider) }}

    {{ form_end(formAddEmploye) }} #}


    {# 3eme affichage #}
    {{ form_start(formAddEmploye) }}

        <div class="row">
            <div class="col-sm">
                {{ form_row(formAddEmploye.nom) }}
            </div>
            <div class="col-sm">
                {{ form_row(formAddEmploye.prenom) }}
            </div>
        </div>
        <div class="row">
            <div class="col-sm">
                {{ form_row(formAddEmploye.dateNaissance) }}
            </div>
            <div class="col-sm">
                {{ form_row(formAddEmploye.dateEmbauche) }}
            </div>
        </div>

        {# on ne modifie pas l'affichage des derniers champs #}
        {{ form_row(formAddEmploye.entreprise) }}
        {{ form_row(formAddEmploye.ville) }}
        {{ form_row(formAddEmploye.valider) }}

    {{ form_end(formAddEmploye) }}

    

    
<!--

https://symfony.com/doc/current/forms.html#rendering-forms 

{# templates/task/new.html.twig #}
\{\{ form(form) }} -> risque de confusion avec la syntaxe form*1(form*2) 
form*1 est le nom de la fonction qui permet de récupérer le formulaire (fonction à appeler pour rendre le formulaire visible) 
l'argument form*2 dedans est le nom de la variable qui provient du controller employe dans la public function new() : 'form' => $form,

on va donc changer le nom de la variable dans le EmployeController pour éviter toute ambiguité : 'form' -> 'formAddEmploye'

-->


{% endblock %}

templates/employe/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détail d'un employé{% endblock %}

{% block body %}

    <h1>Détail d'un employé</h1>  

    <h2>{{ employe }}</h2>
   
    <p>
        Ville : {% if employe.ville %} {{ employe.ville }} {% else %} Ville non renseignée {% endif %} <br>
    
        Date de naissance : {{ employe.dateNaissance | date("m-d-Y") }}<br>

        Age : {{ employe.age }} ans<br>
    
        Date d'embauche : {{ employe.dateEmbauche | date("m-d-Y") }}<br>
    
        Employé par : <a href="{{ path('show_entreprise', {'id' : employe.entreprise.id}) }}">{{ employe.entreprise.raisonSociale }}</a><br>
    </p>

{% endblock %}